<a href="https://colab.research.google.com/github/Dhananjana97/ML-Ride-Fair/blob/master/after_cross_validation.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
from google.colab import drive 
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

# Import common Modules

In [ ]:
import pandas as pd
import numpy as np
import xlrd


import matplotlib.pyplot as plt
from sklearn.metrics import average_precision_score

# FileLoad

In [ ]:
train_df=pd.read_csv('/content/drive/My Drive/ML Project/train.csv');
test_df=pd.read_csv('/content/drive/My Drive/ML Project/test.csv');
submission_df=pd.read_csv('/content/drive/My Drive/ML Project/sample_submission.csv')
train_df.drop_duplicates(inplace = True)
test_df.drop_duplicates(inplace = True)
train_df

          tripid  additional_fare  duration  ...  drop_lon    fare    label
0      189123628             10.5     834.0  ...   79.8783  270.32  correct
1      189125358             10.5     791.0  ...   79.8923  197.85  correct
2      189125719             10.5    1087.0  ...   79.9146  301.64  correct
3      189127273             10.5     598.0  ...   79.8971   82.30  correct
4      189128020              NaN       NaN  ...   79.9290  358.39  correct
...          ...              ...       ...  ...       ...     ...      ...
17171  213803193             10.5     838.0  ...   80.6557  198.26  correct
17172  213812756             10.5    2151.0  ...   79.9389  581.23  correct
17173  213813930             10.5     263.0  ...   79.9017   76.20  correct
17174  213815405             10.5     858.0  ...   79.9010  133.31  correct
17175  213817296             10.5     262.0  ...   79.9374   98.57  correct

[17172 rows x 14 columns]

# Seperate label clumn

In [ ]:
lbl=[]
for index, row in train_df.iterrows():
  label=row['label']
  
  if(label=="correct"):
    lbl.append(1)
  elif(label=="incorrect"):
    lbl.append(0)
lbl

[1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 0,
 0,
 1,
 0,
 1,
 1,
 1,
 1,
 1,
 1,
 0,
 1,
 1,
 1,
 1,
 0,
 0,
 1,
 1,
 1,
 0,
 0,
 1,
 1,
 0,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 0,
 1,
 1,
 0,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 0,
 1,
 1,
 1,
 1,
 0,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 0,
 1,
 1,
 1,
 1,
 0,
 0,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 0,
 1,
 1,
 0,
 1,
 1,
 1,
 1,
 1,
 1,
 0,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 0,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 0,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 0,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 0,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 0,
 1,
 1,
 1,
 0,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 0,
 1,
 0,
 1,
 1,
 1,
 1,
 0,
 1,
 1,
 1,
 1,
 0,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 0,
 1,
 1,
 1,
 1,
 1,
 0,
 0,
 0,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 0,
 0,
 1,
 1,
 0,
 1,
 1,
 1,
 1,
 1,
 1,
 0,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 0,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 0,
 1,
 1,
 1,
 0,
 1,
 1,
 1,
 0,
 1,
 1,
 1,
 1,
 0,
 1,
 0,
 1,
 1,
 1,
 1,
 1,
 1,
 0,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 0,
 1,
 1,
 1,
 1,
 1,
 0,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 0,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 0,
 1,
 0,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 0,
 0,
 1,
 0,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 0,
 1,
 1,
 1,
 1,
 0,
 1,
 1,
 1,
 0,
 1,
 1,
 1,
 1,
 1,
 0,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 0,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 0,
 1,
 1,
 1,
 0,
 1,
 1,
 1,
 1,
 1,
 0,
 1,
 0,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 0,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 0,
 1,
 1,
 1,
 1,
 0,
 1,
 0,
 1,
 1,
 1,
 1,
 1,
 0,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 0,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 0,
 0,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 0,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 0,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 0,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 0,
 1,
 1,
 1,
 1,
 0,
 1,
 1,
 1,
 1,
 0,
 1,
 0,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 0,
 1,
 1,
 0,
 1,
 1,
 1,
 1,
 0,
 1,
 1,
 0,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 0,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 0,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 0,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 0,
 1,
 1,
 1,
 0,
 0,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 0,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 0,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 0,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 0,
 1,
 1,
 1,
 1,
 0,
 1,
 1,
 0,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 0,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 0,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 0,
 0,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 0,
 1,
 1,
 0,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 0,
 1,
 1,
 0,
 0,
 1,
 1,
 1,
 1,
 1,
 0,
 0,
 1,
 0,
 1,
 1,
 0,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 0,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 0,
 1,
 1,
 1,
 1,
 1,
 0,
 1,
 1,
 0,
 1,
 1,
 0,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 0,
 1,
 0,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 0,
 0,
 1,
 1,
 ...]

In [ ]:
train_df['lb']=lbl

In [ ]:
train_df

          tripid  additional_fare  duration  ...    fare    label  lb
0      189123628             10.5     834.0  ...  270.32  correct   1
1      189125358             10.5     791.0  ...  197.85  correct   1
2      189125719             10.5    1087.0  ...  301.64  correct   1
3      189127273             10.5     598.0  ...   82.30  correct   1
4      189128020              NaN       NaN  ...  358.39  correct   1
...          ...              ...       ...  ...     ...      ...  ..
17171  213803193             10.5     838.0  ...  198.26  correct   1
17172  213812756             10.5    2151.0  ...  581.23  correct   1
17173  213813930             10.5     263.0  ...   76.20  correct   1
17174  213815405             10.5     858.0  ...  133.31  correct   1
17175  213817296             10.5     262.0  ...   98.57  correct   1

[17172 rows x 15 columns]

In [ ]:
labels_df=pd.DataFrame(train_df['lb'])
features_df=train_df.drop(labels=['label','lb'],axis=1)
features_df

features_df

          tripid  additional_fare  duration  ...  drop_lat  drop_lon    fare
0      189123628             10.5     834.0  ...   6.90330   79.8783  270.32
1      189125358             10.5     791.0  ...   6.91373   79.8923  197.85
2      189125719             10.5    1087.0  ...   6.93669   79.9146  301.64
3      189127273             10.5     598.0  ...   6.92748   79.8971   82.30
4      189128020              NaN       NaN  ...   6.84478   79.9290  358.39
...          ...              ...       ...  ...       ...       ...     ...
17171  213803193             10.5     838.0  ...   7.28891   80.6557  198.26
17172  213812756             10.5    2151.0  ...   6.95089   79.9389  581.23
17173  213813930             10.5     263.0  ...   7.10135   79.9017   76.20
17174  213815405             10.5     858.0  ...   6.93574   79.9010  133.31
17175  213817296             10.5     262.0  ...   6.90823   79.9374   98.57

[17172 rows x 13 columns]

#Import model related modules

In [ ]:
from sklearn.preprocessing import StandardScaler
from sklearn.impute import SimpleImputer
from sklearn_pandas import CategoricalImputer
from sklearn.compose import ColumnTransformer
from sklearn.pipeline import Pipeline
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import train_test_split
from sklearn import metrics
from sklearn.metrics import f1_score
from sklearn.model_selection import StratifiedKFold
from pprint import pprint
from math import radians, cos, sin, asin, sqrt

# Calc Distance

In [ ]:


def getDistance(df):
  # The math module contains a function named 
    # radians which converts from degrees to radians. 
  dist=[]
  for index, row in df.iterrows():
    lon1 = radians(row['pick_lon']) 
    lon2 = radians(row['drop_lon']) 
    lat1 = radians(row['pick_lat']) 
    lat2 = radians(row['drop_lat']) 
       
    # Haversine formula  
    dlon = lon2 - lon1  
    dlat = lat2 - lat1 
    a = sin(dlat / 2)**2 + cos(lat1) * cos(lat2) * sin(dlon / 2)**2
  
    c = 2 * asin(sqrt(a))  
     
    # Radius of earth in kilometers. Use 3956 for miles 
    r = 6371
       
    # calculate the result 
    distance=c * r
    dist.append(distance)
  
  return dist

In [ ]:
getDistance(features_df)

[5.092769918614749,
 3.1680575840028093,
 6.305395096498956,
 0.8619461197905727,
 8.14778220061441,
 24.207039248887845,
 4.77762352223266,
 5.322543700241312,
 1.0353018356743493,
 2.930715230104055,
 14.381001132845066,
 4.515655217602484,
 9.424518630693273,
 1.4822326128545675,
 1.4400702368954967,
 13.134533272021095,
 5.123992648484041,
 1.2646648169662118,
 9.946708664968586,
 2.4989545167381277,
 2.2814676303202774,
 16.783013705293456,
 1.9297374974341521,
 4.2524115423095665,
 8.774419577321087,
 2.158639601316546,
 0.22512869093339952,
 1.5586563952189847,
 5.044182192380528,
 4.332270836375877,
 2.7020831310547613,
 2.4344507883203668,
 6.095000666312774,
 9.932622235546958,
 0.7754995733372814,
 1.1968734616119863,
 1.955358507262967,
 7.221149247721649,
 6.4991273847408655,
 2.7143833765541463,
 10.804860544656814,
 0.7983078488963857,
 1.5689911732292072,
 0.7124683760151019,
 2.4514238318216366,
 1.7361632222406627,
 0.6001069791989461,
 0.01236083468686051,
 5.563219127638894,
 5.391269071873447,
 2.2770590839620644,
 1.2572520766657131,
 1.5967142221605661,
 9.823777439694982,
 1.4481898524044776,
 8.629788871213757,
 1.0541124659014611,
 6.276075164271725,
 4.196914861480737,
 6.1930055505418045,
 0.02252094023692018,
 1.1798282281551282,
 0.008895594131637,
 0.023835257529558385,
 0.524705010221392,
 0.9222915245034161,
 0.6741623767207382,
 0.13345624592632727,
 1.6990182476950921,
 5.812625423700883,
 0.6171318428773546,
 3.785539704481219,
 19.633709945415852,
 0.03328633069076288,
 12.995602608221358,
 0.5810089503205834,
 2.118453417406355,
 1.0490093814428059,
 2.941141754970175,
 0.5334025032647668,
 1.1726808279617504,
 5.766747991527094,
 0.6294027027383367,
 2.11136394313751,
 3.3156986191967475,
 5.679548206848277,
 0.2201637187088043,
 0.5058896331311465,
 2.8638398500528823,
 8.453706049717056,
 4.274814929553273,
 2.443110657428915,
 1.5561486263940632,
 2.2403548015958665,
 6.204411120840426,
 4.2651776915339275,
 0.022330086813575425,
 4.685815000425823,
 7.7544254575398215,
 4.008103305302631,
 9.350237203866083,
 2.9060220253684053,
 0.02906588156027885,
 1.3382644849985121,
 2.6152623775534405,
 2.251738585228695,
 2.304694923822017,
 0.23446257223136813,
 0.008895594131637,
 11.155490631590373,
 4.597911979016327,
 5.611352866756026,
 7.047735646608311,
 0.013343391197411292,
 14.573734605918425,
 7.949908544995157,
 12.608470636226176,
 4.152565664749214,
 8.828922561439338,
 3.480329112599765,
 2.2617422932394518,
 3.9840810218374383,
 1.2665704532633317,
 3.668657671881112,
 8.760060244984395,
 6.3100263578870335,
 3.588108896513893,
 5.394275370869801,
 1.9123676874852378,
 5.734008684835098,
 4.010621589272888,
 16.353760460498375,
 1.44924838276093,
 12.609706305774015,
 5.995263384181989,
 11.140827324117394,
 11.627245116923518,
 3.8129663326250123,
 1.9962315199412242,
 4.09331692571469,
 6.854422383354054,
 5.3672136677768405,
 0.8943202754632457,
 6.2843626189041215,
 1.0792449552902708,
 1.1577487638629584,
 4.127460028953245,
 0.0,
 6.986878126780552,
 4.013324507277694,
 2.0619642824154862,
 0.023802380560698153,
 19.165013719621285,
 8.052031035662187,
 3.336158750215572,
 0.0,
 3.8021007506052165,
 3.494864182996403,
 1.0788858587165744,
 7.247069947359975,
 1.3549091987683428,
 1.682860336001848,
 9.985018387055202,
 8.936058344596816,
 3.617520166274151,
 4.511059583704964,
 6.5287368449992105,
 6.988725012278156,
 3.404724740468586,
 1.2748914630224193,
 4.671710683006076,
 6.836595948374704,
 0.9388587005616958,
 8.391940651341974,
 5.691660210340512,
 8.225148726929678,
 8.447787021747672,
 0.5504645044393607,
 9.147923689481281,
 9.215628442489047,
 6.005428143168457,
 7.950805343027534,
 1.2462636792540993,
 1.9378764916645856,
 0.8831746709145784,
 4.386384728561811,
 12.24413440399606,
 1.6254964282915059,
 1.49157828751607,
 7.763920359752583,
 5.1299063114537296,
 8.174176316907237,
 1.9037040080554055,
 4.7704624468129415,
 3.962741504698536,
 13.263223157705307,
 2.974950879491079,
 2.067537394820624,
 15.640999946033352,
 5.487228515273666,
 4.229635926823167,
 5.509522474988041,
 1.644614167191831,
 1.2389986566052622,
 6.912457127445364,
 3.9909307288236113,
 3.8790226062760893,
 0.0033358477994412383,
 7.2326782468368975,
 2.519469483345954,
 1.625524894046268,
 0.4385948862207536,
 3.13811898849997,
 22.814196882888854,
 0.03463570029506454,
 3.9131854927912815,
 2.4119587738589034,
 0.6121353986200189,
 2.191527834543042,
 2.491786845607351,
 8.310855757766312,
 4.535366268559759,
 0.9677875872058256,
 0.8365841738232771,
 0.8359094927674006,
 2.7661230827806422,
 0.0022238985329313538,
 0.17362081930466194,
 7.967979489383015,
 1.0706526806240908,
 4.913026670075021,
 0.023064222230023114,
 1.4038663818304544,
 1.5230202432872755,
 8.511220124687725,
 6.854372647334369,
 6.458907138480951,
 0.48815863940070664,
 2.5739846870802237,
 13.126879047840093,
 1.4231984568939668,
 0.8503156682844961,
 6.9861223532938475,
 0.03094599685371233,
 2.178116617206759,
 2.968508823553988,
 4.8631643332237875,
 3.1046684482446465,
 6.924931783780532,
 10.533413491754985,
 0.924485467251698,
 2.3594393145869406,
 2.615784525212347,
 1.2830830871510752,
 1.6343435302750693,
 9.549459227468127,
 4.0793762867195085,
 0.21011997585133851,
 9.964208430029121,
 0.005559746332284177,
 0.7231641307705085,
 1.6012965096265637,
 4.745782390878597,
 4.322900601094985,
 6.768095632502867,
 0.9618956996895884,
 0.4516698322982448,
 9.065863049409927,
 4.103030441079921,
 2.073991698325297,
 1.445957014822091,
 2.0243276978407745,
 11.708903793326844,
 6.720924059222633,
 1.9649621401864803,
 8.978095249453283,
 6.778205832085797,
 10.793530943312557,
 4.502383116941591,
 2.240342402945176,
 4.15747322291091,
 3.491079217473541,
 2.2736397099929064,
 0.012360153026882946,
 7.869788096562083,
 2.373703708252201,
 17.65924758216615,
 0.11482481604055067,
 0.5525504339277153,
 9.195587268359981,
 6.597781653386156,
 5.262952725023949,
 2.795470517075697,
 0.9399916382331749,
 4.1663426651127775,
 0.6602984519444625,
 0.7439052240242958,
 3.5204826550016524,
 5.153014024193786,
 0.9343495276869337,
 0.051593134734662295,
 1.8990567655262325,
 2.820816926225512,
 10.045507265851011,
 4.709140588071178,
 1.2170894092385658,
 0.6786155176449113,
 2.254750264465688,
 2.708364657810853,
 0.956706860840695,
 3.393242271813502,
 10.266585772586758,
 5.633301748451278,
 2.890354811822516,
 11.432271123299628,
 2.107393161647985,
 5.293425749913664,
 7.188536818680405,
 1.705221976125431,
 5.308865341239067,
 0.005559746332195761,
 1.0673027186716013,
 12.233275055117135,
 0.05537072955965256,
 14.578216089730248,
 5.4554608182371975,
 5.251894450861241,
 11.669677973592021,
 3.2575302941090114,
 8.072375271739501,
 12.928274291115228,
 3.2530231034867594,
 6.120648064119696,
 3.7177732667178334,
 4.194361351666727,
 0.010007543398058469,
 7.943988615104825,
 10.034475209066954,
 1.6564901874139426,
 0.7402746388285228,
 3.1435991058854857,
 6.9935681775265985,
 7.206108462397271,
 10.73689355514606,
 6.743005147449954,
 17.51498758707285,
 1.1432964904548304,
 0.1671572565924526,
 4.360017498464223,
 3.401004501596899,
 3.7412278069752376,
 2.160281252322431,
 1.6125146552522611,
 3.9942820127523935,
 2.414702264467201,
 25.462624878160828,
 3.6382446851506547,
 5.915611946765275,
 0.7258610388422825,
 1.5663464315508682,
 0.0951991805459628,
 0.9229839070177808,
 2.9462773263398603,
 3.6474282998336616,
 7.81192583103751,
 0.5907786319316802,
 3.623418393890134,
 12.429032982321008,
 1.6336998930689732,
 1.4889907576059558,
 0.6061032416356616,
 2.1874578184972697,
 0.6348620687442158,
 1.0169779618103507,
 1.435420493722268,
 8.46741412224928,
 0.10468739940161063,
 3.344972323074954,
 4.743166099224324,
 1.2212965039619657,
 1.7108806555430027,
 0.0011119492665983,
 0.5620055936691744,
 0.04553939837266415,
 2.96078844868935,
 0.03358025337308245,
 2.270363105536657,
 0.5561036326052091,
 11.367365746418693,
 3.760611958166508,
 9.915428082181034,
 4.480057172851491,
 6.61767390006564,
 1.1774617199426403,
 2.0810851115554097,
 4.899612922834538,
 4.787670894875894,
 4.3798906718161845,
 2.929129263221579,
 2.6357411900674843,
 2.2805135221079924,
 4.37164566461483,
 1.2714651976452893,
 6.179299174635314,
 4.554424387093022,
 2.7009924118741155,
 0.046203341571022634,
 3.1694793515262107,
 1.3289738174895327,
 2.8704483186883385,
 13.398133051283557,
 0.02211540129350023,
 2.211705304560002,
 0.03329277945149441,
 3.8977951316135084,
 1.2665923161897437,
 0.6561593080438473,
 0.03708102343014691,
 0.5145680975325921,
 2.4463941762058083,
 8.316211284446348,
 1.7182186802545876,
 11.688707235830298,
 5.107402848874244,
 2.4303577918087353,
 0.44418305753698645,
 2.050346640725042,
 1.189302210251148,
 8.480727306514398,
 3.990409824578797,
 5.411078374061452,
 5.034944885432413,
 4.078067187104821,
 4.527688897168542,
 1.8940667981177974,
 0.7804651960245084,
 5.37668277480828,
 10.021611626900054,
 2.087846256147191,
 4.690397617618068,
 17.077242780246,
 0.8878752684239353,
 0.5098612018714316,
 1.8426374170152868,
 3.430563508927283,
 2.795643144084596,
 2.6869031812924455,
 1.8918121092614935,
 2.082607526082635,
 5.336607275270033,
 0.24292549814483322,
 14.89797626797098,
 3.50003587804012,
 4.671787089549607,
 0.7456574415636402,
 3.368230703862919,
 2.356965942273737,
 8.771610836002624,
 18.65146781427773,
 2.745109147352317,
 10.012092033171776,
 3.464631706529953,
 17.237800194640062,
 3.7547668132988212,
 20.4727247398478,
 4.593106067386833,
 1.9221664302414134,
 9.077777603360014,
 6.294334403837185,
 1.0573526616292062,
 1.9438134176285453,
 0.26891405500690957,
 0.43262260066758207,
 7.441626403472907,
 9.484212361859452,
 4.931007338260635,
 16.27980602787562,
 6.637267569127643,
 1.273986014459125,
 3.4389924503080938,
 5.770966743984934,
 8.600667717495584,
 6.1843583232278725,
 4.168866078539339,
 2.799610160375929,
 9.027871695993337,
 11.094508117908354,
 2.1877052732256845,
 0.8196181848535168,
 2.5341534907134267,
 10.638542329837382,
 1.1657320392709574,
 0.535278061970894,
 1.9606326567507162,
 11.024569245157222,
 1.3897839221608117,
 3.4019323301968347,
 1.3913197588022332,
 9.612891859868691,
 1.738292155982427,
 12.943325548847168,
 1.4636218683824878,
 1.4706576241822398,
 2.893196823969869,
 16.90617236012141,
 15.333624726100796,
 15.328530693175498,
 2.855162215300953,
 4.205044207984584,
 4.058826578858826,
 3.9214386107674484,
 2.350594239697582,
 2.482026555206164,
 3.0772806850883714,
 0.1958583535914707,
 2.4756339860088334,
 3.2178453700176237,
 0.012231441931078238,
 4.138250200720485,
 0.01647608366434559,
 0.01818673966372858,
 9.882708097661718,
 2.392170370223995,
 0.8098964529159898,
 3.0252399503152327,
 0.02767089537685861,
 11.4157233416479,
 2.8309957901917504,
 0.03341713518648353,
 1.9136557950188302,
 0.014177400032649622,
 0.12793173143330716,
 1.6396638496561953,
 0.020015086796028522,
 1.630874237684942,
 4.852262095149117,
 0.011119492664391523,
 2.577828274198523,
 2.5922400986337473,
 2.357294328928488,
 0.4300538114366605,
 3.525565046838789,
 3.419878674148559,
 1.5431415272515643,
 1.0624352213920596,
 1.6258737617531462,
 4.11986490036817,
 0.9199990848821521,
 0.10591232329028506,
 1.0881936781277044,
 6.864028203499522,
 1.155194694681863,
 2.31994559887696,
 2.630794059742426,
 3.628054640157755,
 2.0080420949709183,
 2.9175574532241795,
 18.043891767795337,
 7.507407416619048,
 0.7997361900137109,
 4.512897973128902,
 3.457309345953621,
 2.0826271979481104,
 1.328913825260346,
 0.04093488287274723,
 7.996576886930351,
 1.7532053044791724,
 4.1086050722287,
 1.8693170963256955,
 1.0319766748141135,
 0.011119492664391523,
 4.482164412233043,
 1.7352390758548,
 0.8391923283594156,
 2.461783808821649,
 3.852092146218271,
 2.3441521617209986,
 0.1326793299927819,
 5.808895056432549,
 0.8126183662019537,
 2.2277749964144786,
 1.746642537663398,
 2.041544062888619,
 0.7689523843925857,
 1.898560845825954,
 3.2120875157426467,
 0.0022238985329313538,
 1.9713223291225346,
 0.946974395524908,
 3.546568743186902,
 7.479096620894679,
 24.58322130269526,
 0.4814791741357497,
 0.06346845678030857,
 4.2375241989352,
 1.644674160923595,
 0.024241174002147783,
 1.4223071939991017,
 12.10062565005315,
 4.163014971215553,
 6.4597990307171385,
 3.1863844627281543,
 2.818213335766554,
 5.215429760384418,
 1.4382216713553295,
 2.975783146578937,
 0.04554012820004842,
 6.482107265174373,
 3.4438205989515,
 5.652498523978114,
 0.044379625799305086,
 4.161405478737077,
 1.3733226690118623,
 17.239462526785893,
 2.519868981485864,
 2.8535970412741096,
 0.9732661792789705,
 5.682654915195417,
 9.029927889170143,
 2.1755550154007417,
 8.193789677432866,
 0.4653340561041668,
 10.321383583462865,
 3.341874972468066,
 0.0011119492665098846,
 0.03378875045909735,
 1.3574521198227691,
 0.6906733647077551,
 26.490357869351158,
 4.530989253956924,
 7.730293634371851,
 0.45077886835710296,
 2.335249944430443,
 4.92316849046338,
 3.353359775119599,
 1.040282133601972,
 7.627741017156918,
 4.509125167001652,
 2.9897327323408005,
 3.102724125621538,
 1.2402368168660183,
 11.215431801073828,
 0.01566635715143756,
 1.5685962020733122,
 6.094056423409789,
 7.278130911688875,
 9.934034427447614,
 2.3968475632104402,
 5.797040159864287,
 7.520409552094752,
 4.747382663695288,
 0.02380253939476726,
 1.9601080617975069,
 0.813550413656502,
 3.61002255684683,
 0.02472281167639471,
 12.41040338613265,
 4.9329760700465055,
 0.0436703609649177,
 13.23712251119622,
 3.4774120467693805,
 1.8115777558225228,
 1.9962790425718693,
 9.876695298959671,
 8.442895188664673,
 7.367198433760731,
 0.019082304223441798,
 1.6821922215821794,
 6.444379724942637,
 15.321487455908887,
 2.157676547527321,
 3.213103212685399,
 3.200788364213332,
 2.3207222425652767,
 4.668865707503742,
 14.878771963745985,
 2.522521047854604,
 3.0364327277303347,
 3.7531723995459445,
 3.4887638994420813,
 9.057651058430361,
 0.6975143842705714,
 3.698079657050759,
 5.196839055192874,
 4.71640426032891,
 0.9084001052084218,
 7.8454777335505055,
 6.8979558876247085,
 7.376493485923108,
 2.6759469330824768,
 0.45338882045748247,
 13.263518688620167,
 4.735209445683977,
 12.768484259813912,
 12.146531404616626,
 1.7068389935013097,
 7.629578586389913,
 3.3827952236668652,
 12.022237468025015,
 9.914835465304005,
 14.190649008559689,
 6.992328752307511,
 2.2255382936615424,
 6.081073379107438,
 2.8107490390226877,
 0.5034766165813829,
 3.6779935324069206,
 2.072627759505141,
 3.124362692869802,
 3.612060650339155,
 0.9230707445685393,
 1.6839690215832437,
 12.334112242552164,
 8.809226163691555,
 0.5278047799716162,
 2.9955274095854394,
 0.20571061429239257,
 2.4892958999878014,
 1.3538920668230672,
 5.331445326142376,
 1.1092712665597317,
 1.3948075007419176,
 0.9373712002086187,
 2.1712066762708497,
 0.5021632119124034,
 4.487299143115559,
 1.542571421219225,
 0.33090604614302366,
 3.246951097919886,
 10.701661156827784,
 9.303975048177186,
 1.113746451759237,
 5.75129443852626,
 4.455903914246943,
 0.5691556393328181,
 0.3124993870757461,
 1.9754634972800886,
 0.6598197886839186,
 1.4996640025359154,
 0.1749726095772042,
 6.981417354436133,
 5.966388372048583,
 0.06000358585693478,
 4.868601041407309,
 15.742951598196848,
 3.788286955124868,
 0.6711290671889917,
 2.6723993393814927,
 2.9427831592992266,
 13.63187641154288,
 0.28756479875237023,
 2.713016960734598,
 1.0415941865401355,
 16.82808647846826,
 4.258120745396588,
 2.0279988466519425,
 0.37244667020043754,
 0.01190234704735776,
 0.38384839823086686,
 0.3671580058527728,
 12.459177519216798,
 1.5010268943097067,
 5.651142476646075,
 3.984657001926414,
 0.035135353087435046,
 1.3489093260204046,
 1.4149346140201082,
 3.7630608908001855,
 0.3098283122948085,
 2.1240807488108544,
 0.9584059284768515,
 7.706725809836212,
 1.9992188582871617,
 1.2032458567597994,
 0.6142402809191928,
 1.3783933851694863,
 14.588467291314068,
 0.10135546651272927,
 1.9720742640049935,
 1.779128250972457,
 0.011902450535758466,
 1.4415935805493418,
 0.0033358477992644076,
 0.4804889017855371,
 3.7596373350447574,
 9.724101924214562,
 3.7036939451555253,
 13.841012590928958,
 6.901908567640362,
 4.171912488640165,
 0.8063171858068559,
 0.024462883861979645,
 1.7823320349400422,
 0.0011119492663330538,
 1.9088522114935185,
 1.7562579462678949,
 0.7731556902340452,
 8.104522117234731,
 0.8643196160783938,
 2.0438911935974793,
 10.236761067917753,
 1.9752668610866182,
 0.5248089046271585,
 6.121406285381067,
 6.056937175893412,
 3.820715444703788,
 2.384709319848099,
 6.186571096294514,
 2.423717279273714,
 0.6635042617425135,
 7.1002433286980695,
 2.6309552888516556,
 2.296431157458141,
 4.77814249258823,
 2.8632754113472094,
 6.35848888999828,
 0.0258296715412829,
 3.9997424484413586,
 2.2580867619659455,
 2.19796934966625,
 2.535425062421583,
 6.947414776133136,
 3.02943560303649,
 2.5981586187726027,
 12.107254382895444,
 4.997398958046066,
 5.576977347059109,
 2.252760343633677,
 0.025790028962564198,
 3.546191813916092,
 0.5547708567086559,
 4.638180209224773,
 2.7744555478485053,
 6.425852680553961,
 1.7226945769820716,
 2.460975712471134,
 6.195068360041663,
 2.5207996129497534,
 1.2203055988614016,
 3.8351538489229675,
 3.0259990965045342,
 4.179467757646813,
 0.011096121250759258,
 1.8312453203737138,
 1.3667395827642614,
 1.5732482177844895,
 0.38028664912445354,
 0.40341828375474503,
 4.010535207450324,
 12.072558783753895,
 2.6825209836629114,
 3.698160780277528,
 6.152278939825229,
 1.5365914877783056,
 4.698614022706813,
 2.060721585314598,
 2.7308766947631447,
 6.979152307637632,
 15.76416498798288,
 3.020762522788901,
 0.18592397479015021,
 0.008895594131460169,
 5.2767071238001195,
 2.8181084607539373,
 0.028910680927753937,
 4.612610253300199,
 2.27196175291636,
 0.6692875827698198,
 3.767237068047432,
 2.2382065884844633,
 1.5357839221571,
 2.3842746392881944,
 0.8152774342604637,
 18.42373530868808,
 5.605434744253728,
 2.771890572386408,
 2.6042986588028865,
 6.670077535595514,
 2.362491194222048,
 3.702942877574126,
 9.10892618491722,
 9.095678516042438,
 4.273754803565472,
 5.290080739873911,
 1.2287332834383613,
 0.06711646424112952,
 6.986958348778039,
 1.2766586780386073,
 4.278127836289609,
 0.9614410366162883,
 0.012231441930901407,
 3.1501228389750042,
 3.5120122582354623,
 0.034601813885288,
 0.09080805534636743,
 4.351999428641896,
 1.7404605012651733,
 2.9542314555109273,
 0.013509801742989496,
 5.397854432476566,
 9.003263879843598,
 1.3634045443045701,
 5.266979771363098,
 0.03002263019391016,
 4.659871385910543,
 2.120619918974037,
 5.767550065695948,
 3.8806115082300043,
 9.931635651156382,
 0.9492709821608127,
 1.6775846705115443,
 1.2812449721051553,
 5.935669264703585,
 1.7200404582007505,
 0.7834214778938053,
 0.5664251718045109,
 2.630163162922011,
 0.06637567560596855,
 5.735523857401983,
 0.49747687334788365,
 5609.52143995086,
 1.5829651754282095,
 1.3288774723287142,
 3.908247177550735,
 2.685040130730668,
 2.3668308451082467,
 1.9118804473994946,
 3.0313802676191175,
 5.405941679989743,
 0.09328365184341615,
 11.224157753379089,
 0.7979048694656279,
 1.194723340725992,
 1.5946880989305485,
 3.2331163395310916,
 3.02628734787221,
 1.1752411281678887,
 2.6434474849927985,
 0.5868752962509518,
 2.1672584074208143,
 2.701520002233836,
 7.100075804203161,
 1.0093821447762978,
 4.588376876741945,
 2.101845912468403,
 1.7581766874017823,
 0.055378436728690486,
 0.0,
 4.281312953920561,
 3.4438673495885888,
 4.654183873365252,
 0.5481909883574552,
 0.01999755075673454,
 5.600839639944758,
 2.8790962982326938,
 5.370045128919439,
 2.248147565324445,
 0.0033358477994412383,
 3.7120892337246665,
 0.01818255679645989,
 2.299151295694358,
 7.91766875435095,
 0.051657225925739354,
 3.0874771793603593,
 0.48684920357333716,
 7.193853742418287,
 14.779034105560937,
 2.111349261600791,
 5.900933279562279,
 1.4930422003722525,

In [ ]:
features_df['dist']=getDistance(features_df)
features_df

          tripid  additional_fare  duration  ...  drop_lon    fare       dist
0      189123628             10.5     834.0  ...   79.8783  270.32   5.092770
1      189125358             10.5     791.0  ...   79.8923  197.85   3.168058
2      189125719             10.5    1087.0  ...   79.9146  301.64   6.305395
3      189127273             10.5     598.0  ...   79.8971   82.30   0.861946
4      189128020              NaN       NaN  ...   79.9290  358.39   8.147782
...          ...              ...       ...  ...       ...     ...        ...
17171  213803193             10.5     838.0  ...   80.6557  198.26   2.105376
17172  213812756             10.5    2151.0  ...   79.9389  581.23  10.868377
17173  213813930             10.5     263.0  ...   79.9017   76.20   1.045518
17174  213815405             10.5     858.0  ...   79.9010  133.31   2.879077
17175  213817296             10.5     262.0  ...   79.9374   98.57   2.115875

[17172 rows x 14 columns]

# Define featues

In [ ]:
features=['additional_fare','duration','meter_waiting','meter_waiting_fare','meter_waiting_till_pickup','fare','dist']

In [ ]:
final_features_df=features_df[features]
final_features_df

       additional_fare  duration  ...    fare       dist
0                 10.5     834.0  ...  270.32   5.092770
1                 10.5     791.0  ...  197.85   3.168058
2                 10.5    1087.0  ...  301.64   6.305395
3                 10.5     598.0  ...   82.30   0.861946
4                  NaN       NaN  ...  358.39   8.147782
...                ...       ...  ...     ...        ...
17171             10.5     838.0  ...  198.26   2.105376
17172             10.5    2151.0  ...  581.23  10.868377
17173             10.5     263.0  ...   76.20   1.045518
17174             10.5     858.0  ...  133.31   2.879077
17175             10.5     262.0  ...   98.57   2.115875

[17172 rows x 7 columns]

#Preprocess Pipeline

In [ ]:
preprocessing_steps = Pipeline([
    ('standard_scaler', StandardScaler()),
    ('simple_imputer', SimpleImputer(strategy="mean"))
])

preprocessor=ColumnTransformer(
    transformers = [
        ("features", preprocessing_steps, features)
    ],
    remainder = "drop"
)
d=pd.DataFrame(preprocessor.fit_transform(final_features_df))
# d[0].std()
d

                  0             1  ...         5         6
0     -3.253376e-02 -1.070020e-01  ... -0.069913  0.005440
1     -3.253376e-02 -1.122972e-01  ... -0.189631 -0.039301
2     -3.253376e-02 -7.584681e-02  ... -0.018174  0.033627
3     -3.253376e-02 -1.360638e-01  ... -0.380515 -0.092907
4     -1.511175e-17  3.349444e-18  ...  0.075576  0.076454
...             ...           ...  ...       ...       ...
17167 -3.253376e-02 -1.065095e-01  ... -0.188954 -0.064003
17168 -3.253376e-02  5.517756e-02  ...  0.443699  0.139695
17169 -3.253376e-02 -1.773168e-01  ... -0.390592 -0.088640
17170 -3.253376e-02 -1.040466e-01  ... -0.296249 -0.046018
17171 -3.253376e-02 -1.774399e-01  ... -0.353638 -0.063759

[17172 rows x 7 columns]

# model define

In [ ]:
estimator=RandomForestClassifier(bootstrap=False,max_depth=70,max_features='auto',min_samples_leaf=1,min_samples_split=10,n_estimators=1000)

estimator
# rf_random.best_params_

RandomForestClassifier(bootstrap=False, ccp_alpha=0.0, class_weight=None,
                       criterion='gini', max_depth=70, max_features='auto',
                       max_leaf_nodes=None, max_samples=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=10,
                       min_weight_fraction_leaf=0.0, n_estimators=1000,
                       n_jobs=None, oob_score=False, random_state=None,
                       verbose=0, warm_start=False)

#Full pipeline define

In [ ]:
full_Pipeline=Pipeline([
  ("preprocess",preprocessor),
  ("estimator",estimator)
])
labels_df
final_features_df

       additional_fare  duration  ...    fare       dist
0                 10.5     834.0  ...  270.32   5.092770
1                 10.5     791.0  ...  197.85   3.168058
2                 10.5    1087.0  ...  301.64   6.305395
3                 10.5     598.0  ...   82.30   0.861946
4                  NaN       NaN  ...  358.39   8.147782
...                ...       ...  ...     ...        ...
17171             10.5     838.0  ...  198.26   2.105376
17172             10.5    2151.0  ...  581.23  10.868377
17173             10.5     263.0  ...   76.20   1.045518
17174             10.5     858.0  ...  133.31   2.879077
17175             10.5     262.0  ...   98.57   2.115875

[17172 rows x 7 columns]

In [ ]:
# # Number of trees in random forest
# n_estimators = [int(x) for x in np.linspace(start = 100, stop = 1000, num = 12)]
# # Number of features to consider at every split
# max_features = ['auto', 'sqrt']
# # Maximum number of levels in tree
# max_depth = [int(x) for x in np.linspace(10, 110, num = 11)]
# max_depth.append(None)
# # Minimum number of samples required to split a node
# min_samples_split = [2, 5, 10]
# # Minimum number of samples required at each leaf node
# min_samples_leaf = [1, 2, 4]
# # Method of selecting samples for training each tree
# bootstrap = [True, False]


# # Create the random grid
# random_grid = {'estimator__n_estimators': n_estimators,
#                'estimator__max_features': max_features,
#                'estimator__max_depth': max_depth,
#                'estimator__min_samples_split': min_samples_split,
#                'estimator__min_samples_leaf': min_samples_leaf,
#                'estimator__bootstrap': bootstrap}
# pprint(random_grid)

In [ ]:
# from sklearn.model_selection import RandomizedSearchCV


# rf_random = RandomizedSearchCV(estimator = full_Pipeline, param_distributions = random_grid, n_iter = 60, cv = 3, verbose=2, random_state=42)

# rf_random.get_params()

#split dataset

In [ ]:
X_train, X_eval, y_train, y_eval = train_test_split(
    final_features_df,
    labels_df,
    test_size=0.3,
    shuffle=True,
    random_state=6
)

# train model

In [ ]:
np.testing.assert_array_equal(final_features_df.index.values,labels_df.index.values)
# payments_df

In [ ]:
full_Pipeline.fit(X_train,y_train['lb'])

Pipeline(memory=None,
         steps=[('preprocess',
                 ColumnTransformer(n_jobs=None, remainder='drop',
                                   sparse_threshold=0.3,
                                   transformer_weights=None,
                                   transformers=[('features',
                                                  Pipeline(memory=None,
                                                           steps=[('standard_scaler',
                                                                   StandardScaler(copy=True,
                                                                                  with_mean=True,
                                                                                  with_std=True)),
                                                                  ('simple_imputer',
                                                                   SimpleImputer(add_indicator=False,
                                                                                 copy=True,
                                                                                 fill_value=None,
                                                                                 missing_...
                 RandomForestClassifier(bootstrap=False, ccp_alpha=0.0,
                                        class_weight=None, criterion='gini',
                                        max_depth=70, max_features='auto',
                                        max_leaf_nodes=None, max_samples=None,
                                        min_impurity_decrease=0.0,
                                        min_impurity_split=None,
                                        min_samples_leaf=1,
                                        min_samples_split=10,
                                        min_weight_fraction_leaf=0.0,
                                        n_estimators=1000, n_jobs=None,
                                        oob_score=False, random_state=None,
                                        verbose=0, warm_start=False))],
         verbose=False)

In [ ]:
# rf_random.best_params_
X_eval

       additional_fare  duration  ...     fare      dist
14875             10.5     501.0  ...   125.56  2.369449
16774             10.5      38.0  ...    60.50  1.376202
5588              10.5     435.0  ...   121.17  1.843410
916               10.5     708.0  ...   136.99  2.630163
8974              10.5     224.0  ...    67.02  0.973033
...                ...       ...  ...      ...       ...
6493              10.5     211.0  ...    77.12  1.267552
3461              10.5   16663.0  ...  1533.96  0.022521
7397              10.5     721.0  ...   160.94  2.960057
5210              10.5     501.0  ...   119.70  2.392388
10020             10.5    1546.0  ...   284.15  6.490710

[5152 rows x 7 columns]

In [ ]:
y_pred=full_Pipeline.predict(X_eval)
y_pred

array([1, 1, 1, ..., 1, 1, 1])

In [ ]:
full_Pipeline.score(X_eval,y_eval['lb'])

0.9520574534161491

In [ ]:
metrics.SCORERS.keys()

dict_keys(['explained_variance', 'r2', 'max_error', 'neg_median_absolute_error', 'neg_mean_absolute_error', 'neg_mean_squared_error', 'neg_mean_squared_log_error', 'neg_root_mean_squared_error', 'neg_mean_poisson_deviance', 'neg_mean_gamma_deviance', 'accuracy', 'roc_auc', 'roc_auc_ovr', 'roc_auc_ovo', 'roc_auc_ovr_weighted', 'roc_auc_ovo_weighted', 'balanced_accuracy', 'average_precision', 'neg_log_loss', 'neg_brier_score', 'adjusted_rand_score', 'homogeneity_score', 'completeness_score', 'v_measure_score', 'mutual_info_score', 'adjusted_mutual_info_score', 'normalized_mutual_info_score', 'fowlkes_mallows_score', 'precision', 'precision_macro', 'precision_micro', 'precision_samples', 'precision_weighted', 'recall', 'recall_macro', 'recall_micro', 'recall_samples', 'recall_weighted', 'f1', 'f1_macro', 'f1_micro', 'f1_samples', 'f1_weighted', 'jaccard', 'jaccard_macro', 'jaccard_micro', 'jaccard_samples', 'jaccard_weighted'])

In [ ]:
from sklearn.model_selection import cross_val_score
kfold = StratifiedKFold(n_splits=10, random_state=1, shuffle=True)
cv_results = cross_val_score(full_Pipeline, final_features_df, labels_df['lb'], cv=kfold, scoring='f1')
cv_results

array([0.97439181, 0.97525381, 0.9721871 , 0.97157296, 0.97264631,
       0.97497624, 0.97186216, 0.97273304, 0.97063467, 0.97141042])

In [ ]:
cv_results.mean()

0.9727668516787513

In [ ]:
f1_score(y_eval, y_pred)

0.973986308583465

# train for full dataset

In [ ]:
features

['additional_fare',
 'duration',
 'meter_waiting',
 'meter_waiting_fare',
 'meter_waiting_till_pickup',
 'fare',
 'dist']

In [ ]:
test_df['dist']=getDist(test_df)
test_df[features]

      additional_fare  duration  ...     fare      dist
0                10.5       924  ...   289.27  0.060315
1                10.5      4249  ...  1912.70  0.373922
2                10.5      1552  ...   394.00  0.053564
3                10.5       462  ...   154.32  0.029694
4                10.5       814  ...   147.47  0.023427
...               ...       ...  ...      ...       ...
8571             10.5      1723  ...   388.48  0.035632
8572             10.5      1378  ...   379.85  0.068094
8573             10.5       418  ...   112.79  0.018501
8574             10.5      1604  ...   248.46  0.035266
8575             10.5      1698  ...   339.63  0.048913

[8576 rows x 7 columns]

In [ ]:
t=full_Pipeline.predict(test_df[features])
t

array([1, 0, 1, ..., 1, 1, 1])

In [ ]:
submission_df['prediction']=t

In [ ]:
submission_df

         tripid  prediction
0     213284604           1
1     213286352           0
2     213293973           1
3     213294622           1
4     213298687           1
...         ...         ...
8571  222856243           1
8572  222857785           0
8573  222858416           1
8574  222858691           1
8575  222860703           1

[8576 rows x 2 columns]

In [ ]:
submission_df.to_csv("submission_5.csv",index=True)